### ISSUE TITLE
Install could mention libpoppler-cpp-dev requirement

### ISSUE THREAD

**Issue by realalexandergeorgiev** [SySS-Research/smbcrawler#1]
its easy to fix, but libpoppler-cpp-dev doesnt seem to be installed on default installations of kali or ubuntu. readme could contain hint to `apt install libpoppler-cpp-dev`

**Comment by Marshall-Hallenbeck** [comment]
Specifically it's a requirement for `pdftotext` when building and installing. I ran into this as well, but it was a simple fix after looking at `pdftotext`, since that's where the install error was.
