### ISSUE TITLE
Small improvement for secrets.json?

### ISSUE THREAD

**Issue by FLX-0x00** [SySS-Research/smbcrawler#2]
First of all - great tool! For this particular use case I think one of the most complete and smooth working tools for Linux. Like Snaffler but not in C#

In some cases I needed a complete list of the results and the full path to the files with the share name and the line number where the secret is found. I ended up with a custom script, but maybe the secrets.json should also have the full filename and line number where the full_line is located. That way you can create such lists directly, without having to map the IDs to the filenames in the autodownload folders.

Example:

```json
  "0459f797": [
    {
      "description": "'password =' in config",
      "confidence": 70,
      "secret": "RANDOM_PASS",
      "full_line": "password=RANDOM_PASS"
    }
  ],
```
In order to get to a list that looks like:

```
password =' in config: password=RANDOM_PASS on file \\SHARE\FOLDER\file.conf line 55
```
You have to manually map the ID to the filenames in the autodownload. I think it would be more convenient to have a secrets.json that looks like this:

```json
  "0459f797": [
    {
      "description": "'password =' in config",
      "confidence": 70,
      "secret": "RANDOM_PASS",
      "full_line": "password=RANDOM_PASS",
      "full_path": " \\\\SHARE\\FOLDER\\file.conf line",
      "line_matched_at": 55
    }
  ],
```

I hope my point is clear. With this information, the secrets file would be easier to handle with further automated research or reporting. Would be great if this could be included if its easy to implement. Just ping me if there is no time to go into this, then I will get my hands dirty and try to do a PR for it.

For the record, here is the custom script I used for that:

```python
import os
import json
import argparse

def load_secrets(secrets_file):
    with open(secrets_file, 'r') as file:
        return json.load(file)

def search_file_for_secret(file_path, secret_to_search):
    matches = []
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
            for line_num, line in enumerate(file, start=1):
                if secret_to_search in line:
                    matches.append((line_num, line.strip()))
    except Exception as e:
        print(f"Error opening file {file_path}: {e}")
    return matches

def generate_report(secrets_file, directory):
    secrets = load_secrets(secrets_file)
    report = []
    for file_id, secret_list in secrets.items():
        for secret in secret_list:
            secret_desc = secret['description']
            full_line = secret['full_line']
            for root, _, files in os.walk(directory):
                for filename in files:
                    if file_id in filename:
                        file_path = os.path.join(root, filename)
                        relative_path = file_path.replace(directory + os.sep, "")
                        relative_path = relative_path.replace(file_id + ":", "", 1)
                        matches = search_file_for_secret(file_path, full_line)
                        for match in matches:
                            line_number, matched_line = match
                            report.append(f"'{secret_desc}': {full_line} in file {relative_path} at line {line_number}")
    if report:
        for line in report:
            print(line)
    else:
        print("No findings found.")

def main():
    parser = argparse.ArgumentParser(description="Automated report for SMBCrawler results")
    parser.add_argument('-s', '--secrets', required=True, help="Path to secrets.json file")
    parser.add_argument('-d', '--directory', required=True, help="Directory containing files to search")
    args = parser.parse_args()
    generate_report(args.secrets, args.directory)

if __name__ == "__main__":
    main()

```

**Comment by AdrianVollmer** [comment]
Hi Paul,

thanks for your suggestion. I actually have a similar script (separate from the code base) that produces a useful report of all secrets and their location. This is clearly a real need.

 Since I was unsatisfied with how I decided to handle the relations between secrets and files, I actually switched over to a full blown relational SQL database. You can check out the `dev` branch if you like. Even though it has several improvements, I haven't released it yet because it's not quite polished, and I'm still not convinced yet that it is the right way to report this naturally structured data. The HTML output in particular is also quite limited when dealing with the output of the scan of a large network.

If you're willing to test the `dev` branch and provide feedback, I'd be happy to consider it.

The idea of including the line number is definitely something I should look into.

**Comment by FLX-0x00** [comment]
Hi Adrian,

Nice to meet you virtually. Thanks for the input. I will go into the dev branch on the next assessment and give some feedback. For now, I am happy with my little script and that this is actually a thing that is on your list ;)

**Comment by FLX-0x00** [comment]
The development branch offers a more advanced and innovative approach - very nice work! I believe that the line numbering in the secrets report is a valuable feature, particularly when working with larger text files. However, I consider the overall implementation with the database and the reporting section, which uses e.g. JSON, to be excellent. This saves a significant amount of time compared to other tools in the field. I am particularly impressed by the default_profile.yml file, which can be extended with ease. One further point to note is that we frequently encounter unprotected shares containing folders named with 'WindowsImageBackup', which obviously contain backups made with Windows board tools. The presence of this specific folder name should be considered as a potential high value, but I was unable to get the command line to find this directory. Could I ask whether this is something that should be added by default to the code base? I would be very grateful for your advice on this matter.

For now, I will close the issue, as everything works as expected on the current dev branch.

**Comment by AdrianVollmer** [comment]
> I believe that the line numbering in the secrets report is a valuable feature, particularly when working with larger text files.

Agreed, and there are no downsides.

> One further point to note is that we frequently encounter unprotected shares containing folders named with 'WindowsImageBackup', which obviously contain backups made with Windows board tools. The presence of this specific folder name should be considered as a potential high value, but I was unable to get the command line to find this directory. Could I ask whether this is something that should be added by default to the code base?

Sure. Actually, I think this sort of information must be crowd sourced, because the collective experience of all users can help make this tool better. So I'm  sort of relying on community input such  as yours, much appreciated.

Thanks for your helpful and valuable feedback!

**Comment by AdrianVollmer** [comment]
I implemented the changes discussed here and will probably merge `dev` and release next week

**Comment by FLX-0x00** [comment]
Awesome - I will give it a try!
